---
- hosts: localhost

  vars_files:
  - ../defaults/main.yml
  - ../vars/main.yml

  tasks:
  - name: "Create files directory"
    file:
      name: ../files
      state: directory

  - name: "Download tgz file"
    get_url:
      url: '{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_tarball }}'
      dest: '../files/{{ solr_tarball }}'
      force: '{{ solr_force_download | default (false) }}'
